### ISSUE TITLE
[Question] Why do you use the while-loop instead of String.prototype.trim?

### ISSUE THREAD

**Issue by friedemannsommer** [Microsoft/vscode-loader#6]
Wouldn't it easier to use the `String.prototype.trim` method instead of the while loop?
[vscode-loader/src/css.ts](https://github.com/Microsoft/vscode-loader/blob/8f91e224c9f40c36186b696c3aece7948247eb90/src/css.ts#L351)

**Comment by Tyriar** [comment]
Probably because it supported IE9 at some point? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Browser_compatibility

**Comment by friedemannsommer** [comment]
Ah makes sense. Thank you.
